/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.calculadoraresistores;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author user
 */
public class CalculadoraNTC extends javax.swing.JPanel {
private ProgramaResistivos parent;


    public CalculadoraNTC(ProgramaResistivos parent) {
        
        initComponents(); 
        this.parent = parent;  // Guarda referencia del JFrame
       
        aplicarFiltroNumerico(jVmin);
        aplicarFiltroNumerico(jR3);
        aplicarFiltroNumerico(jTVi);
        aplicarFiltroNumerico(jTT1);
        aplicarFiltroNumerico(jTT2);
        aplicarFiltroNumerico(jTNTC1);
        aplicarFiltroNumerico(jTNTC2);
        aplicarFiltroNumerico(jVmax);
        
        URL imgURL = getClass().getResource("/img/info.png");
        System.out.println("Ruta encontrada: " + imgURL);
if (imgURL != null) {
    ImageIcon icono = new ImageIcon(imgURL);
    btnInfo.setIcon(icono);
} else {
    System.err.println("Error: No se encontró la imagen.");
}
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jTVi = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jVmin = new javax.swing.JTextField();
        jTNTC2 = new javax.swing.JTextField();
        jTT2 = new javax.swing.JTextField();
        jTNTC1 = new javax.swing.JTextField();
        jTT1 = new javax.swing.JTextField();
        jR3 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jVmax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnResultados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Rx1 = new javax.swing.JLabel();
        Rx2 = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(590, 520));

        jTVi.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTVi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTVi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Voltaje de alimentación (V)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N
        jTVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTViActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(190, 213, 235));
        btnLimpiar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jVmin.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jVmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jVmin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Voltaje de salida mínimo (V)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N
        jVmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVminActionPerformed(evt);
            }
        });

        jTNTC2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTNTC2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTNTC2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Resistencia (Ω)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        jTT2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTT2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTT2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Temperatura máxima (°C)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        jTNTC1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTNTC1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTNTC1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Resistencia (Ω)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N
        jTNTC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNTC1ActionPerformed(evt);
            }
        });

        jTT1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTT1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTT1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(237, 237, 237), 1, true), "Temperatura mínima (°C)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        jR3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jR3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jR3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Resistencia R3 (Ω)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N
        jR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR3ActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(190, 213, 235));
        btnCalcular.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.setBorderPainted(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jVmax.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jVmax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jVmax.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Voltaje de salida mínimo (V)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Ingresa los valores únicamente en Volts (V) y Ohmios (Ω)");

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora NTC");

        btnResultados.setBackground(new java.awt.Color(190, 213, 235));
        btnResultados.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnResultados.setForeground(new java.awt.Color(255, 255, 255));
        btnResultados.setText("Circuito");
        btnResultados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnResultados.setBorderPainted(false);
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel2.setText("Primera Condición");

        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel3.setText("Segunda Condición");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valores para R2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Candara Light", 1, 18))); // NOI18N

        Rx1.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N

        Rx2.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N

        btnInfo.setBorderPainted(false);
        btnInfo.setContentAreaFilled(false);
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Rx1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(Rx2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Rx1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rx2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contentLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTVi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(jTT1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jVmin, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(18, 18, 18)
                            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jVmax, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(jTT2)))
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                .addComponent(jTNTC1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTNTC2))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(388, 388, 388))
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jR3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTVi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVmin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVmax, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTT2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNTC1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNTC2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jR3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        add(content, "card2");
        content.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents
    private void aplicarFiltroNumerico(JTextField textField) {
        ((AbstractDocument) textField.getDocument()).setDocumentFilter(new NumericFilter());    
    }
    
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
       
        //CONDICIONAL PARA EVALUAR ESPACIOS VACIOS O CARACTERES DIFERENTES
        if(jVmin.getText().isEmpty() || jR3.getText().isEmpty()  ||jTVi.getText().isEmpty() 
         || jTT1.getText().isEmpty() ||jTT2.getText().isEmpty()  ||jTNTC1.getText().isEmpty() 
         ||jTNTC2.getText().isEmpty()|| jVmax.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null,"Error: Rellenar datos correctamente");
            
        }else{
            // Convertir los valores de los JTextField a float
            float Vi = Float.parseFloat(jTVi.getText());
            float Va = Float.parseFloat(jVmin.getText());
            float Vb = Float.parseFloat(jVmax.getText());
            float T = Float.parseFloat(jTT1.getText());
            float TT2 = Float.parseFloat(jTT2.getText());
            float NTC1 = Float.parseFloat(jTNTC1.getText());
            float NTC2 = Float.parseFloat(jTNTC2.getText());
            float R3 = Float.parseFloat(jR3.getText());
            

            if(Vb >= Vi){
               
                 JOptionPane.showMessageDialog(null, "<html>Error: El voltaje de salida<br>"
        + "máximo no debe ser igual<br>"
        + "ni mayor al de entrada.</html>", 
        "Mensaje", JOptionPane.INFORMATION_MESSAGE);

            }else{
                if(Vi<0 || Va<0 || Vb<0 || T<0 || TT2<0 || NTC1<0 || NTC2<0 || R3 <0){
                    JOptionPane.showMessageDialog(null,"Error: Los valores no deben ser negativos");                   
                }else{
                    if(Vi==0 & Va==0 & Vb==0 & T==0 & TT2==0 & NTC1==0 & NTC2==0 & R3==0){
                    JOptionPane.showMessageDialog(null,"Error: Todos los valores ingresados son 0");
                    }else{
                                    //Valores para la ecuación cuadrática
                        float a = (Vb/Vi);
                        System.out.println("a: "+a);
                        float b = (Vb/Vi)*(NTC1+NTC2)-(NTC1-NTC2);
                        System.out.println("b: "+b);
                        float c = (Vb/Vi)*(NTC1*NTC2);
                        System.out.println("c: "+c);

                        //Las excepciones dentro de la ecuación
                        float determinante = b * b - 4*a*c ;
                        float determinante1 = 2*a;

                       // Verificar si los resultados son inválidos antes de continuar
if (determinante < 0 || determinante1 == 0) {
    Rx1.setText("<html> Resultados inválidos o imaginarios <br> para la ecuación cuadrática.</html>");
    Rx2.setText(""); // Limpiar el campo Rx2 para evitar mostrar valores incorrectos
    return; // Detener la ejecución del código si la ecuación no tiene solución real
}

// Se ha determinado que no hay negativos ni imaginarios
float determinante2 = (float) Math.sqrt(determinante);

// Verificar si la raíz cuadrada es NaN (Not a Number)
if (Float.isNaN(determinante2)) {
    Rx1.setText("<html> Resultados inválidos o imaginarios <br> para la ecuación cuadrática.</html>");
    Rx2.setText("");
    return;
}
                        //Se ha determinado que no hay negativos  ni imaginarios

                       
                        float R2x = (-b + determinante2) / determinante1;
                        
                        float R2x2 = (-b-determinante2) / determinante1;

                        System.out.println("x1: "+R2x);
                        System.out.println("x2: "+R2x2);
                
                        Rx1.setText(String.format("Valor de R2x1:  %.0f Ω", R2x));
                        Rx2.setText(String.format("Valor de R2x2:  %.0f Ω", R2x2));

                        
                        System.out.println("NTC1: "+NTC1);

                        float xR2 = R2x/NTC1;
                        float yR2 = R2x2/NTC1;

                        
                        
                    float R1, Vaa, Vaaa, Voo, Vo, Vbb;
                    if(xR2>1){
                    R1 = R3*xR2;
                    System.out.println("Valor de R1: "+R1);
                    System.out.println("Valor de R2: "+R2x);
                    System.out.println("Valor de R3: "+R3);
                    System.out.println("Valor de R4 a 0°C: "+NTC1);
                    System.out.println("Valor de R4 a 100°C: "+NTC2);
                   
                    Vbb = Vi*(R3/(R1+R3));
                    Vaa = Vi*(NTC1/(R2x+NTC1));
                    Vaaa = Vi*(NTC2/(R2x+NTC2));
                    Voo = Vaa - Vbb;
                    Vo = Vaaa - Vbb;
                    System.out.println("Valor de Va: "+Vaa);
                    System.out.println("Valor de Va2: "+Vaaa);
                    System.out.println("Valor de Vb: "+Vbb);
                    System.out.println("Valor de Vo con NTC1: "+Voo);
                    System.out.println("Valor de Vo con NTC2: "+Vo);
                    //jTVo.setText(String.format("%.2f KΩ", Voo));
                    parent.Rntc.setResultado(Vi,R1,R2x,R3, NTC1,NTC2); // Enviamos el número a NTCResultados
                  }if(yR2>1){

                    R1 = R3*yR2;
                    System.out.println("Valor de R1: "+R1);
                    System.out.println("Valor de R2: "+R2x2);
                    System.out.println("Valor de R3: "+R3);
                    System.out.println("Valor de R4 a 0°C: "+NTC1);
                    System.out.println("Valor de R4 a 100°C: "+NTC2);
                    Vbb = Vi*(R3/(R1+R3));
                    Vaaa = Vi*(NTC2/(R2x+NTC2));
                    Vaa = Vi*(NTC1/(R2x2+NTC1));
                    Voo = Vaa - Vbb;
                    Vo = Vaaa - Vbb;
                    System.out.println("Valor de Va: "+Vaa);
                    System.out.println("Valor de Va2: "+Vaaa);
                    System.out.println("Valor de Vb: "+Vbb);
                    System.out.println("Valor de Vo con NTC1: "+Voo);
                    System.out.println("Valor de Vo con NTC2: "+Vo);
                    
                     parent.Rntc.setResultado(Vi,R1,R2x2,R3, NTC1,NTC2); // Enviamos el número a NTCResultados
                   
                }
           


                    }
                }
            } 
        }   
    }//GEN-LAST:event_btnCalcularActionPerformed

    
  

    private void jR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jR3ActionPerformed

    private void jTNTC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNTC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNTC1ActionPerformed

    private void jVminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVminActionPerformed

    // BOTON DE LIMPIAR ESPACIOS 
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
       
        jTVi.setText("");
        jVmin.setText("");
        jVmax.setText("");
        jTT1.setText("");
        jTT2.setText("");
        jVmax.setText("");
        jTNTC1.setText("");
        jTNTC2.setText("");
        jR3.setText("");
        Rx1.setText("");
        Rx2.setText("");
   
    }//GEN-LAST:event_btnLimpiarActionPerformed

    
    private void jTViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTViActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTViActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        parent.showPanel("NTCResultados");
    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        JOptionPane.showMessageDialog(null, "<html>Se debe elegir un valor para <br>"
                                                             + "R2 tal que R2/RNTC0°C >1</html>", 
                                         "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInfoActionPerformed
        
    
   
    
    
    public boolean validarSiPasa(){
        boolean bandera;
        
        if(jVmin.getText().isEmpty() || jR3.getText().isEmpty() ||jTVi.getText().isEmpty() 
           || jTT1.getText().isEmpty() || jTT2.getText().isEmpty() || jTNTC1.getText().isEmpty() 
           || jTNTC2.getText().isEmpty() || jVmax.getText().isEmpty() ) { bandera = true;
        }else {
           bandera = false; 
        }
        
        return bandera;
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Rx1;
    private javax.swing.JLabel Rx2;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnResultados;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jR3;
    private javax.swing.JTextField jTNTC1;
    private javax.swing.JTextField jTNTC2;
    private javax.swing.JTextField jTT1;
    private javax.swing.JTextField jTT2;
    private javax.swing.JTextField jTVi;
    private javax.swing.JTextField jVmax;
    private javax.swing.JTextField jVmin;
    // End of variables declaration//GEN-END:variables
}
