/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.calculadoraresistores;

import java.awt.BorderLayout;
import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Dona
 */
public class CalculadoraRTD extends javax.swing.JPanel {
private ProgramaResistivos parent;
   
    public CalculadoraRTD(ProgramaResistivos parent) {
       
        initComponents();
        this.parent = parent;  // Guarda referencia del JFrame
        aplicarFiltroNumerico(jVmin);
        aplicarFiltroNumerico(jR3);
        aplicarFiltroNumerico(jTVi);
        aplicarFiltroNumerico(jTT1);
        aplicarFiltroNumerico(jTT2);
        aplicarFiltroNumerico(jRTD);
        aplicarFiltroNumerico(jRTD2);
        aplicarFiltroNumerico(jVmax);
         URL imgURL = getClass().getResource("/img/info.png");
if (imgURL != null) {
    ImageIcon icono = new ImageIcon(imgURL);
    btnInfo2.setIcon(icono);
} else {
    System.err.println("Error: No se encontró la imagen.");
}
    
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Rx5 = new javax.swing.JLabel();
        Rx6 = new javax.swing.JLabel();
        btnInfo2 = new javax.swing.JButton();
        jTT1 = new javax.swing.JTextField();
        jR3 = new javax.swing.JTextField();
        jVmax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTVi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jVmin = new javax.swing.JTextField();
        jRTD2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTT2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRTD = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        content.setBackground(new java.awt.Color(255, 255, 255));

        btnLimpiar.setBackground(new java.awt.Color(190, 213, 235));
        btnLimpiar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnResultados.setBackground(new java.awt.Color(190, 213, 235));
        btnResultados.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnResultados.setForeground(new java.awt.Color(255, 255, 255));
        btnResultados.setText("Circuito");
        btnResultados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnResultados.setBorderPainted(false);
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(190, 213, 235));
        btnCalcular.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setText("Calcular");
        btnCalcular.setBorderPainted(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valores para R2", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Candara Light", 1, 18))); // NOI18N

        Rx5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N

        Rx6.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N

        btnInfo2.setBorderPainted(false);
        btnInfo2.setContentAreaFilled(false);
        btnInfo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Rx5, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(Rx6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Rx5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rx6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTT1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTT1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTT1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(237, 237, 237), 1, true), "Temperatura mínima (°C)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        jR3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jR3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jR3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Resistencia R3 (Ω)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N
        jR3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR3ActionPerformed(evt);
            }
        });

        jVmax.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jVmax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jVmax.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Voltaje de salida mínimo (V)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel7.setText("Ingresa los valores únicamente en Volts (V) y Ohmios (Ω)");

        jTVi.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTVi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTVi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Voltaje de alimentación (V)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N
        jTVi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTViActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Calculadora RTD");

        jVmin.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jVmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jVmin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Voltaje de salida mínimo (V)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N
        jVmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVminActionPerformed(evt);
            }
        });

        jRTD2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jRTD2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRTD2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Resistencia (Ω)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel2.setText("Primera Condición");

        jTT2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTT2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTT2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Temperatura máxima (°C)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Candara Light", 1, 18)); // NOI18N
        jLabel3.setText("Segunda Condición");

        jRTD.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jRTD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRTD.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 237, 237)), "Resistencia (Ω)", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Light", 0, 14))); // NOI18N
        jRTD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRTDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTVi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTT1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jVmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jVmax)
                            .addComponent(jTT2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(jRTD, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRTD2))))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                    .addContainerGap(7, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(contentLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jR3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTVi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVmin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVmax, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTT2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRTD, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRTD2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jR3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(523, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
      
        jTVi.setText("");
        jVmin.setText("");
        jVmax.setText("");
        jTT1.setText("");
        jTT2.setText("");
        jVmax.setText("");
        jRTD.setText("");
        jRTD2.setText("");
        jR3.setText("");
        Rx1.setText("");
        Rx2.setText("");

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        parent.showPanel("RTDResultados");
    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        //CONDICIONAL PARA EVALUAR ESPACIOS VACIOS O CARACTERES DIFERENTES
        if(jVmin.getText().isEmpty() || jR3.getText().isEmpty()  ||jTVi.getText().isEmpty()
            || jTT1.getText().isEmpty() ||jTT2.getText().isEmpty()  ||jRTD.getText().isEmpty()
            ||jRTD2.getText().isEmpty()|| jVmax.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null,"Error: Rellenar datos correctamente");

        }else{
            // Convertir los valores de los JTextField a float
            float Vi = Float.parseFloat(jTVi.getText());
            float Va = Float.parseFloat(jVmin.getText());
            float Vb = Float.parseFloat(jVmax.getText());
            float T = Float.parseFloat(jTT1.getText());
            float TT2 = Float.parseFloat(jTT2.getText());
            float NTC1 = Float.parseFloat(jRTD.getText());
            float NTC2 = Float.parseFloat(jRTD2.getText());
            float R3 = Float.parseFloat(jR3.getText());

            if(Vb >= Vi){

                JOptionPane.showMessageDialog(null, "<html>Error: El voltaje de salida<br>"
                    + "máximo no debe ser igual<br>"
                    + "ni mayor al de entrada.</html>",
                    "Mensaje", JOptionPane.INFORMATION_MESSAGE);

            }else{
                if(Vi<0 || Va<0 || Vb<0 || T<0 || TT2<0 || NTC1<0 || NTC2<0 || R3 <0){
                    JOptionPane.showMessageDialog(null,"Error: Los valores no deben ser negativos");
                }else{
                    if(Vi==0 & Va==0 & Vb==0 & T==0 & TT2==0 & NTC1==0 & NTC2==0 & R3==0){
                        JOptionPane.showMessageDialog(null,"Error: Todos los valores ingresados son 0");
                    }else{
                        //Valores para la ecuación cuadrática
                        float a = (Vb/Vi);
                        System.out.println("a: "+a);
                        float b = (Vb/Vi)*(NTC1+NTC2)-(NTC2-NTC1);
                        System.out.println("b: "+b);
                        float c = (Vb/Vi)*(NTC1*NTC2);
                        System.out.println("c: "+c);

                        //Las excepciones dentro de la ecuación
                        float determinante = b * b - 4*a*c ;
                        float determinante1 = 2*a;

                        if (a == 0) {
                            JOptionPane.showMessageDialog(null,"El valor de 'a' no puede ser 0 en una ecuación cuadrática.");
                            throw new IllegalArgumentException("El valor de 'a' no puede ser 0 en una ecuación cuadrática.");
                        }

                        if(determinante < 0){

                        }

                        if(determinante1 <= 0){

                        }

                        //Se ha determinado que no hay negativos  ni imaginarios

                        float determinante2 = (float) Math.sqrt(determinante);

                        float R2x = (-b + determinante2) / determinante1;

                        float R2x2 = (-b-determinante2) / determinante1;

                        System.out.println("x1: "+R2x);
                        System.out.println("x2: "+R2x2);

                        Rx1.setText(String.format("Valor de R2x1:  %.0f Ω", R2x));
                        Rx2.setText(String.format("Valor de R2x2:  %.0f Ω", R2x2));

                        System.out.println("NTC1: "+NTC1);

                        float xR2 = R2x/NTC1;
                        float yR2 = R2x2/NTC1;

                        float R1, Vaa, Vaaa, Voo, Vo, Vbb;
                        if(xR2>1){
                            R1 = R3*xR2;
                            System.out.println("Valor de R1: "+R1);
                            System.out.println("Valor de R2: "+R2x);
                            System.out.println("Valor de R3: "+R3);
                            System.out.println("Valor de R4 a 0°C: "+NTC1);
                            System.out.println("Valor de R4 a 100°C: "+NTC2);

                            Vbb = Vi*(R3/(R1+R3));
                            Vaa = Vi*(NTC1/(R2x+NTC1));
                            Vaaa = Vi*(NTC2/(R2x+NTC2));
                            Voo = Vaa - Vbb;
                            Vo = Vaaa - Vbb;
                            System.out.println("Valor de Va: "+Vaa);
                            System.out.println("Valor de Va2: "+Vaaa);
                            System.out.println("Valor de Vb: "+Vbb);
                            System.out.println("Valor de Vo con NTC1: "+Voo);
                            System.out.println("Valor de Vo con NTC2: "+Vo);
                            //jTVo.setText(String.format("%.2f KΩ", Voo));
                            parent.Rntc.setResultado(Vi,R1,R2x,R3, NTC1,NTC2); // Enviamos el número a NTCResultados
                        }if(yR2>1){

                            R1 = R3*yR2;
                            System.out.println("Valor de R1: "+R1);
                            System.out.println("Valor de R2: "+R2x2);
                            System.out.println("Valor de R3: "+R3);
                            System.out.println("Valor de R4 a 0°C: "+NTC1);
                            System.out.println("Valor de R4 a 100°C: "+NTC2);
                            Vbb = Vi*(R3/(R1+R3));
                            Vaaa = Vi*(NTC2/(R2x+NTC2));
                            Vaa = Vi*(NTC1/(R2x2+NTC1));
                            Voo = Vaa - Vbb;
                            Vo = Vaaa - Vbb;
                            System.out.println("Valor de Va: "+Vaa);
                            System.out.println("Valor de Va2: "+Vaaa);
                            System.out.println("Valor de Vb: "+Vbb);
                            System.out.println("Valor de Vo con NTC1: "+Voo);
                            System.out.println("Valor de Vo con NTC2: "+Vo);

                            parent.Rntc.setResultado(Vi,R1,R2x2,R3, NTC1,NTC2); // Enviamos el número a NTCResultados

                        }

                    }
                }
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnInfo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfo2ActionPerformed
        JOptionPane.showMessageDialog(null, "<html>Se debe elegir un valor para <br>"
            + "R2 tal que R2/RNTC0°C >1</html>",
            "Mensaje", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInfo2ActionPerformed

    private void jR3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jR3ActionPerformed

    private void jTViActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTViActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTViActionPerformed

    private void jVminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVminActionPerformed

    private void jRTDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRTDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRTDActionPerformed

    private void aplicarFiltroNumerico(JTextField textField) {
        ((AbstractDocument) textField.getDocument()).setDocumentFilter(new NumericFilter());    
    }
    private boolean isClicked = false;
   
    
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Rx1;
    private javax.swing.JLabel Rx2;
    private javax.swing.JLabel Rx3;
    private javax.swing.JLabel Rx4;
    private javax.swing.JLabel Rx5;
    private javax.swing.JLabel Rx6;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnInfo1;
    private javax.swing.JButton btnInfo2;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnResultados;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jR3;
    private javax.swing.JTextField jRTD;
    private javax.swing.JTextField jRTD2;
    private javax.swing.JTextField jTT1;
    private javax.swing.JTextField jTT2;
    private javax.swing.JTextField jTVi;
    private javax.swing.JTextField jVmax;
    private javax.swing.JTextField jVmin;
    // End of variables declaration//GEN-END:variables
}
